[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["ZaminOS"]
description = "ZaminOS kernel — Rust, aarch64, mobile-first konvergent OS"

[dependencies]
aarch64-cpu = "9"
tock-registers = "0.8"
linked_list_allocator = "0.10"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
