[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["ZaminOS"]
description = "ZaminOS kernel — Rust, aarch64, mobile-first konvergent OS"

[dependencies]
aarch64-cpu = "9"
tock-registers = "0.8"
linked_list_allocator = "0.10"
font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }
noto-sans-mono-bitmap = { version = "0.3", default-features = false, features = ["regular", "bold", "size_16", "size_20", "size_24", "size_32", "unicode-basic-latin"] }
virtio-drivers = "0.7"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
